x-llama-cpp-base: &llama-cpp-base
  image: ghcr.io/ggml-org/llama.cpp:server-cuda
  ports:
    - 8080:8080
  networks:
    default:
      aliases:
        - inference
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: ["gpu"]
  healthcheck:
    test: ["CMD-SHELL", "curl -fsS http://localhost:8080/v1/models || exit 1"]
    interval: 120s
    timeout: 120s
    retries: 4
    start_period: 120s

x-llama-cpp-common-env: &llama-cpp-common-env
  LLAMA_ARG_CTX_SIZE: 32768
  LLAMA_ARG_N_GPU_LAYERS: 99
  LLAMA_ARG_PORT: 8080

x-pipeline-common-env: &pipeline-common-env
  SERVER_ADDRESS: "http://inference:8080/v1"
  EVAL_ITERATIONS: ${EVAL_ITERATIONS}
  EVAL_PIPELINE: ${EVAL_PIPELINE}
  EVAL_DOMAIN: ${EVAL_DOMAIN}

x-pipeline-base: &pipeline-base
  build: .
  volumes:
    - ./logs:/app/logs
    - ./pddl:/app/pddl
    - ./plans:/app/plans
    - ./results:/app/results

services:
  qwen_25_coder:
    <<: *llama-cpp-base
    profiles: ["qwen-2.5-coder"]
    command:
      - "--jinja"
      - "--top-k"
      - "20"
      - "--top-p"
      - "0.8"
      - "--temp"
      - "0.7"
      - "--min-p"
      - "0.0"
      - "--flash-attn"
      - "on"
      - "--presence-penalty"
      - "1.5"
    environment:
      <<: *llama-cpp-common-env
      LLAMA_ARG_HF_REPO: unsloth/Qwen2.5-Coder-14B-Instruct-128K-GGUF:q4_k_m

  qwen_3_vl:
    <<: *llama-cpp-base
    profiles: ["qwen-3-vl"]
    command:
      - "--jinja"
      - "--top-k"
      - "20"
      - "--top-p"
      - "0.8"
      - "--temp"
      - "0.7"
      - "--flash-attn"
      - "on"
    environment:
      <<: *llama-cpp-common-env
      LLAMA_ARG_HF_REPO: unsloth/Qwen3-VL-8B-Instruct-GGUF:q4_k_m

  qwen_3:
    <<: *llama-cpp-base
    profiles: ["qwen_3"]
    command:
      - "--jinja"
      - "--top-k"
      - "20"
      - "--min-p"
      - "0.0"
      - "--top-p"
      - "0.95"
      - "--temp"
      - "0.6"
      - "--flash-attn"
      - "on"
    environment:
      <<: *llama-cpp-common-env
      LLAMA_ARG_HF_REPO: unsloth/Qwen3-14B-GGUF:q4_k_m

  gemma3:
    <<: *llama-cpp-base
    profiles: ["gemma3"]
    command:
      - "--jinja"
      - "--temp"
      - "1.0"
      - "--repeat-penalty"
      - "1.0"
      - "--min-p"
      - "0.01"
      - "--top-k"
      - "64"
      - "--top-p"
      - "0.95"
      - "--flash-attn"
      - "on"
    environment:
      <<: *llama-cpp-common-env
      LLAMA_ARG_HF_REPO: unsloth/gemma-3-12b-it-GGUF:q5_k_m

  gpt_oss:
    <<: *llama-cpp-base
    profiles: ["gpt-oss"]
    command:
      - "--jinja"
      - "--temp"
      - "1.0"
      - "--top-k"
      - "0"
      - "--top-p"
      - "1.0"
      - "--flash-attn"
      - "on"
    environment:
      <<: *llama-cpp-common-env
      LLAMA_ARG_HF_REPO: unsloth/gpt-oss-20b-GGUF:q4_k_m

  pipeline_qwen_25_coder:
    <<: *pipeline-base
    profiles: ["qwen-2.5-coder"]
    depends_on:
      qwen_25_coder:
        condition: service_healthy
    environment:
      <<: *pipeline-common-env
      EVAL_MODEL: "qwen-2.5-coder"

  pipeline_qwen_3_vl:
    <<: *pipeline-base
    profiles: ["qwen-3-vl"]
    depends_on:
      qwen_3_vl:
        condition: service_healthy
    environment:
      <<: *pipeline-common-env
      EVAL_MODEL: "qwen-3-vl"

  pipeline_qwen_3:
    <<: *pipeline-base
    profiles: ["qwen-3"]
    depends_on:
      qwen_3:
        condition: service_healthy
    environment:
      <<: *pipeline-common-env
      EVAL_MODEL: "qwen-3"

  pipeline_gemma3:
    <<: *pipeline-base
    profiles: ["gemma3"]
    depends_on:
      gemma3:
        condition: service_healthy
    environment:
      <<: *pipeline-common-env
      EVAL_MODEL: "gemma3"

  pipeline_gpt_oss:
    <<: *pipeline-base
    profiles: ["gpt-oss"]
    depends_on:
      gpt_oss:
        condition: service_healthy
    environment:
      <<: *pipeline-common-env
      EVAL_MODEL: "gpt-oss"
