from src.base.schemas import Domains, Images, Problems, Prompts

DOMAIN_PROMPTS = {
    Domains.RING_AND_PEG: Prompts.RING_AND_PEG_DOMAIN,
    Domains.NEEDLE_TRANSFER: Prompts.NEEDLE_TRANSFER_DOMAIN,
    Domains.NEEDLE_SORTING: Prompts.NEEDLE_SORTING_DOMAIN,
}

PROBLEM_PROMPTS = {
    Problems.RING_AND_PEG_1: Prompts.RING_AND_PEG_1,
    Problems.RING_AND_PEG_2: Prompts.RING_AND_PEG_2,
    Problems.RING_AND_PEG_3: Prompts.RING_AND_PEG_3,
    Problems.RING_AND_PEG_4: Prompts.RING_AND_PEG_4,
    Problems.RING_AND_PEG_5: Prompts.RING_AND_PEG_5,
    Problems.NEEDLE_TRANSFER_1: Prompts.NEEDLE_TRANSFER_1,
    Problems.NEEDLE_TRANSFER_2: Prompts.NEEDLE_TRANSFER_2,
    Problems.NEEDLE_SORTING_1: Prompts.NEEDLE_SORTING_1,
    Problems.NEEDLE_SORTING_2: Prompts.NEEDLE_SORTING_2,
    Problems.NEEDLE_SORTING_3: Prompts.NEEDLE_SORTING_3,
}

ACTION_SCHEMA_PROMPTS = {
    Domains.RING_AND_PEG: Prompts.ACTION_SCHEMA_RING_AND_PEG,
    Domains.NEEDLE_TRANSFER: Prompts.ACTION_SCHEMA_NEEDLE_TRANSFER,
    Domains.NEEDLE_SORTING: Prompts.ACTION_SCHEMA_NEEDLE_SORTING,
}

OBJECT_NAME_PROMPTS = {
    Domains.NEEDLE_TRANSFER: Prompts.OBJECT_NAMES_NEEDLE_TRANSFER,
    Domains.RING_AND_PEG: Prompts.OBJECT_NAMES_RING_AND_PEG,
    Domains.NEEDLE_SORTING: Prompts.OBJECT_NAMES_NEEDLE_SORTING,
}

IMAGES = {
    Problems.RING_AND_PEG_1: Images.RING_AND_PEG_1,
    Problems.RING_AND_PEG_2: Images.RING_AND_PEG_2,
    Problems.RING_AND_PEG_3: Images.RING_AND_PEG_3,
    Problems.RING_AND_PEG_4: Images.RING_AND_PEG_4,
    Problems.RING_AND_PEG_5: Images.RING_AND_PEG_5,
    Problems.NEEDLE_TRANSFER_1: Images.NEEDLE_TRANSFER_1,
    Problems.NEEDLE_TRANSFER_2: Images.NEEDLE_TRANSFER_2,
    Problems.NEEDLE_SORTING_1: Images.NEEDLE_SORTING_1,
    Problems.NEEDLE_SORTING_2: Images.NEEDLE_SORTING_2,
    Problems.NEEDLE_SORTING_3: Images.NEEDLE_SORTING_3,
}
